Update to Assignment 1 script The following update: -	fixes an issue where if the user does not follow instructions for pressing the enter key at the start, the script will crash -	fixes an issue where if the user simply leaves the domain prompt blank that the script will crash -	fixed redirect for pkg check to redirect to stderr and other related redirections -	added test for rndc reload so that the script doesn't assume the rndc reload was successful. It would only test if the domains worked on a successful reload. -	fixed mail A record IP - whoops! -	auto generate serial numbers based on the date the zone files were created -	script has a new feature called -checkdom to allow the user to quickly check a domain without re-running the entire script. This feature does not require root -	script now checks for the SOA of each domain and reports to the user if one is found or not

diff --git a/Assignment1 b/Assignment1
--- a/Assignment1
+++ b/Assignment1
@@ -18,7 +18,7 @@ fi
 
 # We must check/install bind9 if it is not already installed.
 function bind_pkg_check {
-dpkg -L bind9 >/dev/null
+dpkg -L bind9 >& /dev/null
 if [ $? != "0" ] ; then
 	echo "Bind not installed!"
 	echo "We will now install bind."
@@ -40,7 +40,7 @@ if [ ! -e /etc/bind/db.$domain ]; then
 ;
 \$TTL	604800
 @	IN	SOA	ns1.$domain. hostmaster.$domain. (
-		     2015010100		; Serial
+		     $SERIAL		; Serial
 			 604800		; Refresh
 			  86400		; Retry
 			2419200		; Expire
@@ -50,7 +50,7 @@ if [ ! -e /etc/bind/db.$domain ]; then
 ns1	IN	A	$ns1_ip
 ;
 www	IN	A	$www_ip
-mail	IN	A	192.168.5.20
+mail	IN	A	$mail_ip
 EOF
 	cat > /etc/bind/db.${ns1_ip_cidr} <<EOF
 ;
@@ -58,7 +58,7 @@ EOF
 ;
 \$TTL	604800
 @	IN	SOA	ns1.$domain. hostmaster.$domain. (
-		     2015010100		; Serial
+		     $SERIAL		; Serial
 			 604800		; Refresh
 			  86400		; Retry
 			2419200		; Expire
@@ -73,7 +73,7 @@ EOF
 ;
 \$TTL	604800
 @	IN	SOA	ns1.$domain. hostmaster.$domain. (
-		     2015010100		; Serial
+		     $SERIAL		; Serial
 			 604800		; Refresh
 			  86400		; Retry
 			2419200		; Expire
@@ -88,7 +88,7 @@ EOF
 ;
 \$TTL	604800
 @	IN	SOA	ns1.$domain. hostmaster.$domain. (
-		     2015010100		; Serial
+		     $SERIAL		; Serial
 			 604800		; Refresh
 			  86400		; Retry
 			2419200		; Expire
@@ -117,35 +117,69 @@ zone "${mail_ip_rev}.in-addr.arpa" {
 };
 EOF
 	rndc reload
+	if [ $? != "0" ] ; then
+		echo "RNDC reload failed!"
+		exit 1
+	else
 	echo " - done"
+	fi
 fi
 }
 
 function dns_check {
 # Function to check if your newly created DNS domains are reachable
+# If the user uses -checkdom as a command line argument, they will be asked to enter a domain to check for
+# NOTE: This function alone DOES NOT require root
+if [ -z $domain ] ; then
+	read -p "Please enter the domain you wish to check: " domain
+fi
 nslookup $domain localhost >/dev/null
 if [ $? != "0" ] ; then
-	echo "$domain is not reachable via DNS"
+	echo "$domain is not reachable via DNS - A record not found"
 else
-	echo "$domain is reachable via localhost"
+	echo "$domain is reachable via localhost - A record found"
 fi
 nslookup ns1.$domain localhost >/dev/null
 if [ $? != "0" ] ; then
-        echo "ns1.$domain is not reachable via DNS"
+        echo "ns1.$domain is not reachable via DNS - A record not found"
 else
-	echo "ns1.$domain is reachable via localhost"
+	echo "ns1.$domain is reachable via localhost - A record found"
 fi
 nslookup www.$domain localhost >/dev/null
 if [ $? != "0" ] ; then
-        echo "www.$domain is not reachable via DNS"
+        echo "www.$domain is not reachable via DNS - A record not found"
 else
-	echo "www.$domain is reachable via localhost"
+	echo "www.$domain is reachable via localhost - A record found"
 fi
 nslookup mail.$domain localhost >/dev/null
 if [ $? != "0" ] ; then
-        echo "mail.$domain is not reachable via DNS"
+        echo "mail.$domain is not reachable via DNS - A record not found"
 else
-	echo "mail.$domain is reachable via localhost"
+	echo "mail.$domain is reachable via localhost - A record found"
+fi
+nslookup -querytype=SOA $domain localhost >/dev/null
+if [ $? != "0" ] ; then
+	echo "$domain is not reachable via DNS - SOA not found"
+else
+	echo "$domain is reachable via localhost - SOA found"
+fi
+nslookup -querytype=SOA ns1.$domain localhost >/dev/null
+if [ $? != "0" ] ; then
+        echo "ns1.$domain is not reachable via DNS - SOA not found"
+else
+        echo "ns1.$domain is reachable via localhost - SOA found"
+fi
+nslookup -querytype=SOA www.$domain localhost >/dev/null
+if [ $? != "0" ] ; then
+        echo "www.$domain is not reachable via DNS - SOA not found"
+else
+        echo "www.$domain is reachable via localhost - SOA found"
+fi
+nslookup -querytype=SOA mail.$domain localhost >/dev/null
+if [ $? != "0" ] ; then
+        echo "mail.$domain is not reachable via DNS - SOA not found"
+else
+        echo "mail.$domain is reachable via localhost - SOA found"
 fi
 }
 #vars
@@ -162,7 +196,7 @@ www_ip_rev="47.168.192" # Used when creating arpa files
 mail_ip="192.168.59.5" # IP for mail
 mail_ip_cidr="192.168.59" # IP for mail in network ID format
 mail_ip_rev="59.168.192" # Used when creating arpa files
-
+SERIAL=$(date +"%Y%m%d")00
 
 ### Main ###
 # This script is for the first assignment and is for creating DNS zones
@@ -177,6 +211,10 @@ until [ "$pressenter_key" = "" ] ; do
 	echo "What did I say??"
 	pressenter
 done
+if [ $1 == "-checkdom" ] ; then
+	dns_check
+	exit
+fi
 # In order for this script to run effectivly, we must make sure this user is root
 # The root ID is always 0
 until [ "$UID" = "0" ] ; do
@@ -210,12 +248,16 @@ else
 	echo "The IP address for mail.$domain is $mail_ip. Its network ID is $mail_ip_cidr."
 	echo "The arpa IP for mail.$domain is $mail_ip_rev."
 	read -p "Are these settings correct? [y/n]" confirm
-	if [ $confirm == "y" ] ; then
+	if [ -z $confirm ] ; then
+		echo "You can't leave this blank. Please try again!"
+		exit 2
+	fi
+	if [ $confirm = "y" ] ; then
 		echo "Okay let's create the zones and files needed!"
 		domain_setup
 		echo "Running check to see if our domains are reachable...."
 		dns_check
-	elif [ $confirm == "n" ] ; then
+	elif [ $confirm = "n" ] ; then
 		echo "Please come back later"
 		exit 0
 	else
